### ISSUE TITLE
Voie verte totalement ecartée de l'analyse.

### ISSUE THREAD

**Issue by Ephtolens** [laem/villes.plus#116]
En imposant le segregated=yes, tu écartes l'ensemble des voies vertes qui sont tagués de la manière suivante sur OSM:

highway=path
bicycle=designated
foot=designated
**segregated=no**

Il faut donc a mon avis enlever la contrainte sur le segregated.
Pour n'ajouter que les vraies voies verte large, on peut ajouter les contraintes:
traffic_sign=FR:C115 -> indique que le panneau voie verte est présent
width>=3 -> la voie verte fait au moins 3m de large

https://github.com/laem/villes.plus/blob/dec09b726f84cdcd53b56623da577250351ceba0/isSafePath.js#LL24C39-L24C39

**Comment by laem** [comment]
Bonjour, merci pour ta contribution ! N'hésite pas à faire une recherche dans les issues avant d'en créer une : c'est un problème bien connu et difficile à résoudre. 

Cf https://github.com/laem/villes.plus/issues/87

Je me permets donc de fermer, et réintroduit l'idée du panneau.
