### ISSUE TITLE
Afficher l'historique des notes

### ISSUE THREAD

**Issue by mquandalle** [laem/villes.plus#117]
**Quel est votre idée, votre problème, votre suggestion ?**

Pouvoir accéder aux notes des mois / années précédentes pour suivre la progression.

**Comment by laem** [comment]
C'est en ligne ! Du moins pour l'avant dernière note.

**Comment by laem** [comment]
Ça ressemble à ça 
![image](https://github.com/laem/villes.plus/assets/1177762/eef1cfea-8533-4a65-88db-46f1eae46d93)

Pour l'instant, en algo v3, il n'y a que juin et septembre de calculés, d'où l'affichage d'un chiffre seulement. 

C'est ce que tu avais en tête, ou c'était autre chose ?

**Comment by mquandalle** [comment]
👍  J'avais pas d'UI en tête, peut-être un graphique quand il y aura un peu plus d'historique
