### ISSUE TITLE
[REV] Intégrer le ReVE de Bordeaux Métropole

### ISSUE THREAD

**Issue by paulop33** [laem/villes.plus#153]
Hello @laem,

Je viens de publier un geojson contenant les coordonnées du ReVE de la métropole de Bordeaux sur un dépôt de Vélo-Cité Bordeaux Métropole

Tu le trouveras ici : 
https://raw.githubusercontent.com/velo-cite/observatoire/main/public/reve_bxmetro.geojson
Dans les données il y a un MultiLineString, qui n'est pas (il me semble) compatible avec le code de villes.plus. 
Il a été obtenu en divisant un LineString pour changer le "status" d'une portion.
2 possibilités : corriger les datas générées de mon coté ou adapté villes.plus. 
Comme les datas ont été généré via umap, il est peut être préférable d'accepter les MultiLineString, ici. 
Je peux essayer d'y jeter un oeil, si besoin. 

Le geojson possède une property "status" qui n'est pas encore fiable. Il va, d'ailleurs, y avoir un sujet d’harmonisation sur ce champ.

Petite diversion : 
Gros sujet sur "ma" métropole : les couloirs de bus sont autorisés dans le référentiel du projet (si moins d'un bus toutes les 10 min). Bref, la qualité d'un REV à l'autre ne sera pas forcément la même.

Merci pour le super taf déjà réalisé jusque là !
  Paul

**Comment by laem** [comment]
Salut @paulop33. Désolé pour le temps que j'ai mis à l'intégrer, mais c'est désormais en ligne ! 

Voilà l'algo : https://github.com/laem/villes.plus/blob/master/web/app/cyclables/[ville]/getRev.ts#L9-L28

Comme tu le vois, c'est simple. J'ai mis en gris les lignes sans couleur. N'hésite pas à les MAJ, il suffira alors de redéployer villes plus en un clic pour que les nouvelles couleurs mises dans "properties._umap_options" ou dans "stroke" directement. 

![image](https://github.com/laem/villes.plus/assets/1177762/153c345c-b4fe-49a4-b9bf-195076af2d2c)
