### ISSUE TITLE
Classements désordonnés

### ISSUE THREAD

**Issue by afranke** [laem/villes.plus#168]
Le [classement des métropoles](https://www.villes.plus/cyclables/metropoles) est incorrect. Métropole du Grand Paris en premier avec seulement 2,3/10, puis Aix-Marseille-Provence avec 0,7/10… Bordeaux Métropole est 8e alors qu’elle a le plus haut score du classement, 4/10.z

Même problème sur le classement des préfectures, alors que celui des grandes villes est correct.

**Comment by laem** [comment]
Salut ! Merci bcp pour le message, il y a en effet un gros bug de génération de la page, suite à une mise à jour des scores. Je m'en occupe.

**Comment by laem** [comment]
OK, c'est bon ! Encore merxci

**Comment by afranke** [comment]
Merci à toi !
