### ISSUE TITLE
Parcs péri-urbains

### ISSUE THREAD

**Issue by laem** [laem/villes.plus#4]
On pense à Vincennes et Boulogne : d'immenses parcs de 10km² en bordure de ville qui ne peuvent pas vraiment être considérés comme des zones piétonnes urbaines. Si ?

Si Paris gagne 10km² avec Vincennes, une foret en bordure de ville ou meme une mer (Marseille, Brest, Nice) pourrait aussi être comptée.

**Comment by adipasquale** [comment]
les trois champions (paris, dijon, le mans) ont tous un ou deux parcs peri urbains super grands.
je trouve que ça rend tout le classement un peu faussé, on ne compare pas les mêmes choses. 

Propositions :
1. exclure manuellement les grands parcs purement et simplement. écrire "on exclut les grands parcs". je pense que les résultats ne seront que plus pertinents par rapport à maintenant.
2. rajouter une colonne booléene "a des parcs extra urbains" cochée / décochée selon les villes. Je pense qu'en aucun sens ça a du sens de comparer la taille des parcs extra urbains donc il ne faut jamais les inclure dans le calcul. par contre l'info est intéressante qualitativement.

**Comment by laem** [comment]
Carrément, c'est ça que j'avais en-tête. Je stocke les formes avant et après fusion (on les fusionne avant de calculer la surface pour éviter les doublons). 

Pour construire cette liste d'id, je comptais utiliser ces formes avant fusion pour pouvoir en mode débug sur la page /VILLE inspecter les formes et noter les ids à exlcure.
