### ISSUE TITLE
Augmenter le nombre de points de calcul

### ISSUE THREAD

**Issue by laem** [laem/villes.plus#64]
Le calcul se fait aujourd'hui seulement sur les 4 mairies adjacentes, pour ne pas faire exploser la combinatoire du calcul. Il faudrait l'augmenter pour 6 au moins je pense, pour éviter des trous, par exemple comme à Grenoble sud. Reste à gérer les calculs supplémentaires, en sachant que le seveur crashe régulièrement en période de mise à jour. On pourrait simplement différerer les calculs de chaque ville :)

**Comment by laem** [comment]
Voir [ici](https://twitter.com/macquaria/status/1609944153999216645) une grosse remise en question du principe actuel de faire le calcul sur tous les points `townhall` d'OSM. 

Se limiter à une seule mairie, qu'on mettrait à la main, c'est trop problématique je pense, car il y a plein de mairie d'arrondissement (pour les super grosses villes, 3) et de quartier qui sont pertinentes. 

Par exemple, Lambézellec à Brest qui est un vrai centre névralgique du quartier. 

Peut-être que les tags OSM nous permettent de faire le tri automatiquement ? 

Peut-être qu'on peut choisir les mairies importantes, puis ajouter d'autres points automatiquement ? 

Peut-être qu'il faut passer à une méthode entièrement manuelle ?

**Comment by laem** [comment]
## Illustrations du problème. 

Ici le centre de Bordeaux, très peuplé n'est presque pas mesuré ! 

![image](https://user-images.githubusercontent.com/1177762/216307594-a1b864b9-0439-4047-b271-f9b04e8bd66f.png)
![image](https://user-images.githubusercontent.com/1177762/216307786-ba0e97a8-032e-4aed-b20b-248ad4025255.png)

Ici à Rennes sud, il n'y a aucune mesure. Pourtant, la densité de population y est très forte ! En particulier, aucune radiale sud.  

![image](https://user-images.githubusercontent.com/1177762/216307885-559f5fab-fb80-49f3-aeef-f39384872607.png)

**Comment by laem** [comment]
On ne peut pas non plus générer des points aléatoirement. Ils se retrouveraient dans des champs, sur des autoroutes, dans des parcs, des lacs...

**Comment by laem** [comment]
Idée : les arrêts de bus ! Contrairement aux métros et tram, les bus sont présents sur tout le territoire. 

On pourrait bien sûr garder les mairies pour les communes les plus démunies, qui n'ont même pas d'arrêt de bus.

Par contre, ça en fera beaucoup beaucoup. On pourrait simplement en garder en proportion : cela permettrait de pondérer les km mesurés par une mesure non pas seulement de la densité de population, mais aussi des bassins d'emploi. 

Bien sûr, on peut aussi garder tram et métro quand il y en a. Par exemple, dans le centre-ville de Rennes, le métro a éradiqué le bus, sauf une petite navette électrique.

**Comment by laem** [comment]
L'algorithme pourrait être le suivant : 
- on télécharge tous les points d'arrêts de bus
- on applique un algo de cluster, qui préserve une proportionnalité du nombre

S'assurer que ça ne créée pas plus d'inégalités de mesure en les zones, que l'actuel avec les mairies.

**Comment by laem** [comment]
Il y a fort à parier que pour préserver les arrêts des plus petits clusters, il faille faire exploser le nombre de requêtes en ville. 

Il me faut un outil pour designer cet algo.

**Comment by laem** [comment]
Ici une belle illustration de la variabilité. 

Comme prévu, augmenter les points, ici pour Brest, via une sélection au hasard de 100 des arrêts de bus de la métropole, ajoute des trajets pertinents ! On gagne des trajets à Guilers, Plouzané, etc et c'est très bien. N'ayant qu'une mairie, ces trajets étaient négligés. 

Par contre, on se rend compte que la sélection au hasard créée des trous : Saint-Pierre et Lambé ne sont plus reliés par La Cavale. C'est un problème. 

Il est facile à régler : on doit garder les points "mairie", et on peut même forcer la trace des itinéraires entre les mairies adjacentes. Étant bien plus éloignées que les arrêts de bus entre eux, on créée alors une liste d'itinéraires à tester plus structurantes du réseau. On pourrait faire de même pour les arrêts de métro ou tram. On s'attendrait alors à y voir les réseaux express vélo en construction. La question de les sur-pondérer se pose, je crois. 

Cela dit, rappelons-nous que si plusieurs itinéraires partagent les mêmes segments, alors cela augmente leur pondération. 

De manière générale, ce nouveau classement augmente la surface de test dans des îlots de quartiers qui n'étaient pas entre deux mairies. Il est donc bien plus représentatif, mais désavantage les mairies qui ne s'occupent que des grands axes. 

C'est le cas de Brest Métropole ! Et je trouve cela très bien de faire un classement qui inclus plus de km. 

![image](https://user-images.githubusercontent.com/1177762/218157207-35b1950e-0192-4da8-a781-dcd5047bfbd5.png)

![image](https://user-images.githubusercontent.com/1177762/218157281-371fbffe-e8a5-435c-b6b7-a4326d7e860e.png)

**Comment by laem** [comment]
Un autre run de Brest avec les bus nous fait passer de 6% à 8%. C'est intéressant, l'ordre de grandeur semble rester valide. 

![image](https://user-images.githubusercontent.com/1177762/218159252-d74ebda1-a418-4fb8-a649-513baf024ebc.png)

Encore un troisième, et on atteint les 10% du classement par mairie. 

![image](https://user-images.githubusercontent.com/1177762/218159618-b0ab6e9e-be77-44f8-bca7-4bd4d9a595ab.png)


À l'inverse, sur Rennes on passe de 18% (mairies) à 23% et encore 27% avec les 100 arrêts de bus. Donc l'inverse de Brest. 


Pour Strasbourg, sur un essai, on passe de 34% à 41% ! Cela semble confirmer que les métropoles considérées cyclables y gagnent, et les autres y perdent. 

![image](https://user-images.githubusercontent.com/1177762/218161417-d0e0f048-67b7-4ad6-8d0b-5cdd2068afa7.png)

![image](https://user-images.githubusercontent.com/1177762/218161534-06f5e088-c4f5-4791-81d3-ecb406da1ca8.png)

**Comment by laem** [comment]
Un autre point : la nouvelle sélection des points nous permet enfin de tester les communes ! 
Exemple avec Rennes. Surprise : ce n'est pas nettement mieux. Eh oui, car beaucoup de points étaient gagnés sur les longues liaisons inter-ville qui étaient équipées. 

![image](https://user-images.githubusercontent.com/1177762/218161917-838b22d0-4593-4950-bb4c-179da6cd9cf3.png)

Bordeaux, qui profitait notamment d'une très longue voie cyclable vers la mer, y perd également, passant de 34 en mairie-métropole à 21% (!) en arrêt de bus - commune. 

À suivre...

**Comment by laem** [comment]
Faire tourner la sélection de points sur des entités administratives de tailles très différentes est lourd d'enseignements. 

Ici sur la Bretagne, vs Rennes, vs Landerneau, on voit très bien l'effet du choix de 100 points de transports seulement. 100 points, cela semble faible. À l'inverse, à Landerneau, il y a si peu d'arrêts...

![image](https://user-images.githubusercontent.com/1177762/221366767-029b21eb-7fc9-4306-908e-938063eddf25.png)

![image](https://user-images.githubusercontent.com/1177762/221366953-03416fb9-c2b4-4214-aa3b-c8d04644c93f.png)

![image](https://user-images.githubusercontent.com/1177762/221366935-0642a7e1-e3fa-4206-93c2-07c66329ab2a.png)

On pourrait paramétrer le nombre d'arrêts de transport sélectionnés avec le nombre de mairies, pour augmenter le nombre de points de transport sur Rennes et Bretagne. On pourrait même dans un premier temps le plafonner par le nombre de mairies de la zone considérée, mais avec un minimum de 100 (ou 10 ou 50 ?) pour les petites zones genre une seule commune. À creuser.

**Comment by laem** [comment]
Attention, dans les captures précédentes, il y avait un problème : tous les arrêts de bus n'étaient pas pris en compte. 

Cette capture illustre bien l'intérêt de comptabiliser les mairies pour les calculs se faisant à l'échelle supérieure à une commune : les arrêts de bus sont rares dans le rural. Ainsi, la sélection random des bus représente la densité de population, et les mairies représentent une couverture minimum du rural. Bien sûr, il y a des arrêts de bus pour chaque mairie, ou presque, en France. Mais l'affichage des mairies reste intéressant ne serait-ce que pour la lecture de la carte, et pour l'importance de la liaison exclusive mairie - mairie (l'algo est codé comme ça). 

![image](https://user-images.githubusercontent.com/1177762/221409522-c1710717-c24b-47b5-92dc-6b54e70c8773.png)

**Comment by laem** [comment]
Cette image de Landivisiau montre bien l'intérêt d'ajouter les arrêts de bus : sans cela, le coeur de la communauté de commune ne serait qu'à peine testé, alors que c'est là que la plupart des gens vivent. Les mairies permettent de tester tout le territoire. 

![image](https://user-images.githubusercontent.com/1177762/222441668-9f195c84-5363-4c79-adb1-762d9f113e17.png)

**Comment by laem** [comment]
Il me semble remarquable que le nombre d'arrêts de bus, qu'il soit à 50 ou 100, ne change pas l'ordre de grandeur du score de cyclabilité. 

Ainsi, avec 50 arrêts, Paris est à 36%. Avec 100, 32%. On reteste avec 50 (la sélection des arrêts est aléatoire !), on obtient 34%. À nouveau, 37%. Encore : 32%. Avec 100 points : 34%. En mode interactif, on voit le score converger *très rapidement* vers un point presque fixe. 

Saint-Étienne métro, dernière du classement v1 avec 2% (!!) : 3%. On re-teste : 4%. Avec 100 points : 3%. 

Testons Nice, une autre métropole dans les choux : 7%. Re-test : 6%. Avec 100 points : 7%. 

**La conclusion est simple : la variabilité entre les tests est suffisamment faible par rapport à l'échelle, 100%.**

Bien sûr, il serait bon de faire pour chaque ville une moyenne de 10 tests, mais pour la v2, ça complique pas mal les choses en termes de ressources serveur...

**Comment by laem** [comment]
Le bas de la métropole de Nice vaut le coup d'oeil : merci la promenade des Anglais !

![image](https://user-images.githubusercontent.com/1177762/222480852-54629c27-138d-4b54-8c8d-9b0963d07bea.png)

**Comment by laem** [comment]
En conclusion, on va adopter un algo relativement simple : 
- toutes les mairies du territoire (tant pis pour les "fausses mairies", elles seront noyées dans le total)
- au moins 100 arrêts de bus, si tant est qu'il y en a 100. Si le nombre de mairies est supérieur (test d'une grande métro, d'un département), alors

**Comment by mquandalle** [comment]
Sur le choix des arrêts de bus comme points de départs et d'arrivée d'itinéraires vélo, je me demande si ça peut introduire un biais défavorable à des trajets sans voitures sur lesquels par définition il n'y a pas d'arrêt de bus. C'est le cas des centres piétons de certaines métropoles (aucun arrêt de bus dans le centre de Bordeaux alors que c'est super cyclable).

Ça peut être intéressant de tester l'algo sur des cas simplifiés ? Par exemple une route voiture / bus parallèle à une voie verte, les 2 routes sont reliées ensemble tous les 500m, est-ce que l'algo prend bien la voie verte ?

**Comment by laem** [comment]
Réglé dans #73  :)
